print('Please enter the following')
print()
adjective=input('adjective:')
animal=input('animal:')
#好像要帶入一樣的詞時不用在分照順序但我這裡加上1,2,3
verb1=input('verb:')
exclamation=input('exclamation:')
verb2=input('verb:')
verb3=input('verb:')
print()
print('Your story is:')
print()
#原定想法為直接在print打出句子+填上的字，在這試試看先以'句子'代替
sentence1=('Few days ago, I was really in trouble.')
sentence2=('It all started when I saw a very')
print(sentence1+' '+sentence2)
sentence3=('In my room. "')
sentence4=('!"I yelled. But all')
snetence5=('I could think to do was to')
sentence6=('over and over. Miraculously,')
sentence7=('that caused it to stop, but not before it tried to')
sentence8=('right in front of my family.')
print(adjective.lower()+' '+animal.lower()+' '+verb1.lower()+' '+sentence3+exclamation.capitalize()+sentence4)
print(snetence5+' '+verb2.lower()+' '+sentence6)
print(sentence7+' '+verb3.lower()+' '+sentence8)