'''
Author:  Bernie Zhong
File: W04 Assignment.py
Objective: Meal Price Calculator
'''
print('You bring your family to a restaurant.')
print('The waiter give you a greeting and ask.')
print(':How many people is the table for?')
print('Then you anwser.....')
Q3=input('We have (number_of_kids:)\n')
print("children and")  
Q4=input('and(number_of_adluts:)\n') 
print('adlut.') 
print()
print('Then waiter guide you to yuor table and gives you the menu. ')
print()
print('|~~~~~~~~~~~~~~~~~~~|~~~~~~~~~~~~~~~~~~~|')
print('|==================Menu=================|')
print('|*****Main meal*****|    | Welcome  |   |')
print("|*Steak        $250 |    | To       |   |")
print("|*Rost pork    $250 |    | Bernie's |   |") 
print('|*             $    |    | Kichen   |   |')  
print('|****Child meal*****|           Tax:_5%_|')
print('|*Surprise~    $150 |  Enjoy your meal!!|')
print('|___________________|___________________|')
print()
#Q5=input("What's the sales tax rate?")(old)
Q5=input("After the ordering, you saw there's tax with(tax:))")
print('on the menu.')
print()
print('=================Eating=================')
print()
print('After the eating, you called the waiter to help makeing payment')
Q1=input("What's the price of a child's meal?")
Q2=input("What's the price of an adult's meal?")
print("Then the waiter gives you the bill")
稅轉小數=(float(Q5)*float(0.01))
未含稅總和=str(int(Q1)*int(Q3)+int(Q2)*int(Q4))
print()
print('|---------------~')
print(f'|Subtotal:${未含稅總和}~')
#note:str(數字與文字相串)int(數字運算)=>兩者相加公式為:str(int(數字)+int(數字))
#python在算數時會follow先乘除後加減這個rule喔!
稅額=(float(稅轉小數)*float(未含稅總和))
print(f'|Sales Tax:${稅額}~')
總額=(float(未含稅總和)+float(稅額))
print(f'|Total :${總額}~')
print('|_______________~')
print()
Q6=input("What's the payment amount?")
print("Get "+Q6+' from you.')
print("Here's Change:$"+str(float(Q6)-float(總額)))
print()
print('See you next time!!')